name: shop_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.4.0
  cloud_functions: ^5.3.0
  firebase_auth: ^5.4.0
  fl_chart: ^0.70.2
  intl: ^0.20.1
  firebase_core: ^3.10.1
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  file_picker: ^8.3.6
  firebase_storage: ^12.4.2
  flutter_barcode_scanner: ^2.0.0
  web_socket_channel: ^3.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png 
  fonts:
    - family: times new roman 
      fonts: 
        - asset: assets/fonts/times new roman.ttf
        - asset: assets/fonts/times new roman italic.ttf
        - asset: assets/fonts/times new roman bold.ttf
          weight: 700
        - asset: assets/fonts/times new roman bold italic.ttf

    