// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC16_GdUkDACZf5rzg-7iYG7ECP3-lPBsI',
    appId: '1:1047465411718:web:0639d5085a409104327d07',
    messagingSenderId: '1047465411718',
    projectId: 'shop-app-257e0',
    authDomain: 'shop-app-257e0.firebaseapp.com',
    storageBucket: 'shop-app-257e0.firebasestorage.app',
    measurementId: 'G-Q525RJRTDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB09QmKTILqOBW-Qw48g-a1ATcy5PozV1Q',
    appId: '1:1047465411718:android:44498fd7b87f5d8b327d07',
    messagingSenderId: '1047465411718',
    projectId: 'shop-app-257e0',
    storageBucket: 'shop-app-257e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnsayY3JQLvW5CxRHWTVtTUkK2nV0I4mQ',
    appId: '1:1047465411718:ios:d98e9b8101e50cb4327d07',
    messagingSenderId: '1047465411718',
    projectId: 'shop-app-257e0',
    storageBucket: 'shop-app-257e0.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnsayY3JQLvW5CxRHWTVtTUkK2nV0I4mQ',
    appId: '1:1047465411718:ios:d98e9b8101e50cb4327d07',
    messagingSenderId: '1047465411718',
    projectId: 'shop-app-257e0',
    storageBucket: 'shop-app-257e0.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC16_GdUkDACZf5rzg-7iYG7ECP3-lPBsI',
    appId: '1:1047465411718:web:14b04a727d922d25327d07',
    messagingSenderId: '1047465411718',
    projectId: 'shop-app-257e0',
    authDomain: 'shop-app-257e0.firebaseapp.com',
    storageBucket: 'shop-app-257e0.firebasestorage.app',
    measurementId: 'G-REEC0KS0HQ',
  );
}
